# Über dieses Projekt {.unnumbered}

Dies ist eine laufende Demonstration eines Workflows für die Erstellung von Glossaren, die Speicherung von Linked Open Data, die Ausgabe in mehreren Formaten und die Verwendung von Glossaren für die Datenanalyse - zum Beispiel für die Suche in Open-Literature-Beständen.

Weitere Informationen über die Entwicklung des Workflows finden Sie [hier](https://github.com/TIBHannover/semantic-glossar).

Ein in Bearbeitung befindliches Beispiel [(semantisches Glossar)](cosite001.ipynb) ist ebenfalls enthalten. Bei dieser Demonstration handelt es sich um ein Glossar, das mit Hilfe einer verknüpften offenen Datenspeicherung verwaltet wird. 

Als Maßstab wurde das Glossar [Climate Change Terms](resources/cct.qmd) der US Environmental Protection Agency, @epa_climate_2013, verwendet. Die EPA verwendet einen [Terminologieservice und Leitfaden](https://www.epa.gov/web-policies-and-procedures/web-standard-glossaries) zur Erstellung und Speicherung ihrer Webglossare.
