# EPA: Begriffe zum Klimawandel

## EPA (US: Environmental Protection Agency)

Name: Glossar der Begriffe zum Klimawandel

Beschreibung: Glossar der auf der EPA-Website zum Klimawandel verwendeten Begriffe.

Veröffentlichende Organisation: Office of Air and Radiation/Office of Atmospheric Protection/Climate Change Division

Letzte Aktualisierung: 9. September 2013

Programm-Website: [https://www.epa.gov/climate-research](https://www.epa.gov/climate-research)

Terminologieservice: [Link](https://sor.epa.gov/sor_internet/registry/termreg/searchandretrieve/glossariesandkeywordlists/search.do?details=&vocabName=Glossary%20Climate%20Change%20Terms)

## Terms

### 100-Year Flood Levels

Severe flood levels with a one-in-100 likelihood of occurring in any given year.

### Abrupt Climate Change

Sudden (on the order of decades), large changes in some major component of the climate system, with rapid, widespread effects.

### Adaptation

Adjustment or preparation of natural or human systems to a new or changing environment which moderates harm or exploits beneficial opportunities.

### Adaptive Capacity

The ability of a system to adjust to climate change (including climate variability and extremes) to moderate potential damages, to take advantage of opportunities, or to cope with the consequences.

### Aerosols

Small particles or liquid droplets in the atmosphere that can absorb or reflect sunlight depending on their composition.

### Afforestation

Planting of new forests on lands that historically have not contained forests.

### Albedo

The amount of solar radiation reflected from an object or surface, often expressed as a percentage.

### Alternative Energy

Energy derived from nontraditional sources (e.g., compressed natural gas, solar, hydroelectric, wind).

### Annex I Countries/Parties

Group of countries included in Annex I (as amended in 1998) to the United Nations Framework Convention on Climate Change, including all the developed countries in the Organization of Economic Co-operation and Development, and economies in transition. By default, the other countries are referred to as Non-Annex I countries. Under Articles 4.2 (a) and 4.2 (b) of the Convention, Annex I countries commit themselves specifically to the aim of returning individually or jointly to their 1990 levels of greenhouse gas emissions by the year 2000.

### Anthropogenic

Made by people or resulting from human activities. Usually used in the context of emissions that are produced as a result of human activities.

### Atmosphere

The gaseous envelope surrounding the Earth. The dry atmosphere consists almost entirely of nitrogen (78.1% volume mixing ratio) and oxygen (20.9% volume mixing ratio), together with a number of trace gases, such as argon (0.93% volume mixing ratio), helium, radiatively active greenhouse gases such as carbon dioxide (0.035% volume mixing ratio), and ozone. In addition the atmosphere contains water vapor, whose amount is highly variable but typically 1% volume mixing ratio. The atmosphere also contains clouds and aerosols.

### Atmospheric Lifetime

Atmospheric lifetime is the average time that a molecule resides in the atmosphere before it is removed by chemical reaction or deposition. In general, if a quantity of a compound is emitted into the atmosphere at a particular time, about 35 percent of that quantity will remain in the atmosphere at the end of the compound's atmospheric lifetime. This fraction will continue to decrease in an exponential way, so that about 15 percent of the quantity will remain at the end of two times the atmospheric lifetime, etc. (Some compounds, most notably carbon dioxide, have more complex lifecycles, and their atmospheric lifetimes are not defined by a simple exponential equation.) Greenhouse gas lifetimes can range from a few years to a few thousand years.

### Biofuels

Gas or liquid fuel made from plant material (biomass). Includes wood, wood waste, wood liquors, peat, railroad ties, wood sludge, spent sulfite liquors, agricultural waste, straw, tires, fish oils, tall oil, sludge waste, waste alcohol, municipal solid waste, landfill gases, other waste, and ethanol blended into motor gasoline.

### Biogeochemical Cycle

Movements through the Earth system of key chemical constituents essential to life, such as carbon, nitrogen, oxygen, and phosphorus.

### Biomass

Materials that are biological in origin, including organic material (both living and dead) from above and below ground, for example, trees, crops, grasses, tree litter, roots, and animals and animal waste.

### Biosphere

The part of the Earth system comprising all ecosystems and living organisms, in the atmosphere, on land (terrestrial biosphere) or in the oceans (marine biosphere), including derived dead organic matter, such as litter, soil organic matter and oceanic detritus.

### Black Carbon Aerosol

Black carbon (BC) is the most strongly light-absorbing component of particulate matter (PM), and is formed by the incomplete combustion of fossil fuels, biofuels, and biomass. It is emitted directly into the atmosphere in the form of fine particles (PM2.5).

### Borehole

Any exploratory hole drilled into the Earth or ice to gather geophysical data. Climate researchers often take ice core samples, a type of borehole, to predict atmospheric composition in earlier years. See ice core.

### Carbon Capture and Sequestration

Carbon capture and sequestration (CCS) is a set of technologies that can greatly reduce carbon dioxide emissions from new and existing coal- and gas-fired power plants, industrial processes, and other stationary sources of carbon dioxide. It is a three-step process that includes capture of carbon dioxide from power plants or industrial sources; transport of the captured and compressed carbon dioxide (usually in pipelines); and underground injection and geologic sequestration, or permanent storage, of that carbon dioxide in rock formations that contain tiny openings or pores that trap and hold the carbon dioxide.

CCS

### Carbon Cycle

All parts (reservoirs) and fluxes of carbon. The cycle is usually thought of as four main reservoirs of carbon interconnected by pathways of exchange. The reservoirs are the atmosphere, terrestrial biosphere (usually includes freshwater systems), oceans, and sediments (includes fossil fuels). The annual movements of carbon, the carbon exchanges between reservoirs, occur because of various chemical, physical, geological, and biological processes. The ocean contains the largest pool of carbon near the surface of the Earth, but most of that pool is not involved with rapid exchange with the atmosphere.

### Carbon Dioxide

A naturally occurring gas, and also a by-product of burning fossil fuels and biomass, as well as land-use changes and other industrial processes. It is the principal human caused greenhouse gas that affects the Earth's radiative balance. It is the reference gas against which other greenhouse gases are measured and therefore has a Global Warming Potential of 1. See climate change and global warming.

### Carbon Dioxide Equivalent

A metric measure used to compare the emissions from various greenhouse gases based upon their global warming potential (GWP). Carbon dioxide equivalents are commonly expressed as "million metric tons of carbon dioxide equivalents (MMTCO₂Eq)." The carbon dioxide equivalent for a gas is derived by multiplying the tons of the gas by the associated GWP. MMTCO₂Eq = (million metric tons of a gas) \* (GWP of the gas) See greenhouse gas, global warming potential, metric ton.

### Carbon Dioxide Fertilization

The enhancement of the growth of plants as a result of increased atmospheric CO₂ concentration. Depending on their mechanism of photosynthesis, certain types of plants are more sensitive to changes in atmospheric CO₂ concentration.

### Carbon Footprint

The total amount of greenhouse gases that are emitted into the atmosphere each year by a person, family, building, organization, or company. A persons carbon footprint includes greenhouse gas emissions from fuel that an individual burns directly, such as by heating a home or riding in a car. It also includes greenhouse gases that come from producing the goods or services that the individual uses, including emissions from power plants that make electricity, factories that make products, and landfills where trash gets sent.

### Carbon Sequestration

Terrestrial, or biologic, carbon sequestration is the process by which trees and plants absorb carbon dioxide, release the oxygen, and store the carbon. Geologic sequestration is one step in the process of carbon capture and sequestration (CCS), and involves injecting carbon dioxide deep underground where it stays permanently.

### Chlorofluorocarbons

Gases covered under the 1987 Montreal Protocol and used for refrigeration, air conditioning, packaging, insulation, solvents, or aerosol propellants. Since they are not destroyed in the lower atmosphere, CFCs drift into the upper atmosphere where, given suitable conditions, they break down ozone. These gases are being replaced by other compounds: hydrochlorofluorocarbons, an interim replacement for CFCs that are also covered under the Montreal Protocol, and hydrofluorocarbons, which are covered under the Kyoto Protocol. All these substances are also greenhouse gases. See hydrochlorofluorocarbons, hydrofluorocarbons, perfluorocarbons, ozone depleting substance.

### Climate

Climate in a narrow sense is usually defined as the "average weather," or more rigorously, as the statistical description in terms of the mean and variability of relevant quantities over a period of time ranging from months to thousands of years. The classical period is 3 decades, as defined by the World Meteorological Organization (WMO). These quantities are most often surface variables such as temperature, precipitation, and wind. Climate in a wider sense is the state, including a statistical description, of the climate system. See weather.

### Climate Change

Climate change refers to any significant change in the measures of climate lasting for an extended period of time. In other words, climate change includes major changes in temperature, precipitation, or wind patterns, among others, that occur over several decades or longer.

### Climate Feedback

A process that acts to amplify or reduce direct warming or cooling effects.

### Climate Lag

The delay that occurs in climate change as a result of some factor that changes only very slowly. For example, the effects of releasing more carbon dioxide into the atmosphere occur gradually over time because the ocean takes a long time to warm up in response to a change in radiation. See climate, climate change.

### Climate Model

A quantitative way of representing the interactions of the atmosphere, oceans, land surface, and ice. Models can range from relatively simple to quite comprehensive. See General Circulation Model.

### Climate Sensitivity

In Intergovernmental Panel on Climate Change (IPCC) reports, equilibrium climate sensitivity refers to the equilibrium change in global mean surface temperature following a doubling of the atmospheric (equivalent) CO₂ concentration. More generally, equilibrium climate sensitivity refers to the equilibrium change in surface air temperature following a unit change in radiative forcing (degrees Celsius, per watts per square meter, °C/Wm-2). One method of evaluating the equilibrium climate sensitivity requires very long simulations with Coupled General Circulation Models (Climate model). The effective climate sensitivity is a related measure that circumvents this requirement. It is evaluated from model output for evolving non-equilibrium conditions. It is a measure of the strengths of the feedbacks at a particular time and may vary with forcing history and climate state. See climate, radiative forcing.

### Climate System

The five physical components (atmosphere, hydrosphere, cryosphere, lithosphere, and biosphere) that are responsible for the climate and its variations.

### Co-Benefit

The benefits of policies that are implemented for various reasons at the same time including climate change mitigation acknowledging that most policies designed to address greenhouse gas mitigation also have other, often at least equally important, rationales (e.g., related to objectives of development, sustainability, and equity).

### Coal Mine Methane

Coal mine methane is the subset of coalbed methane that is released from the coal seams during the process of coal mining. For more information, visit the Coalbed Methane Outreach program site \[http://www.epa.gov/cmop/\].

### Coalbed Methane

Coalbed methane is methane contained in coal seams, and is often referred to as virgin coalbed methane, or coal seam gas. For more information, visit the Coalbed Methane Outreach program site \[http://www.epa.gov/cmop/\].

### Concentration

Amount of a chemical in a particular volume or weight of air, water, soil, or other medium. See parts per billion, parts per million.

### Conference of the Parties

The supreme body of the United Nations Framework Convention on Climate Change (UNFCCC). It comprises more than 180 nations that have ratified the Convention. Its first session was held in Berlin, Germany, in 1995 and it is expected to continue meeting on a yearly basis. The COP's role is to promote and review the implementation of the Convention. It will periodically review existing commitments in light of the Convention's objective, new scientific findings, and the effectiveness of national climate change programs. See United Nations Framework Convention on Climate Change.

### Coral Bleaching

The process in which a coral colony, under environmental stress expels the microscopic algae (zooxanthellae) that live in symbiosis with their host organisms (polyps). The affected coral colony appears whitened.

### Cryosphere

One of the interrelated components of the Earth's system, the cryosphere is frozen water in the form of snow, permanently frozen ground (permafrost), floating ice, and glaciers. Fluctuations in the volume of the cryosphere cause changes in ocean sea level, which directly impact the atmosphere and biosphere.

### Deforestation

Those practices or processes that result in the conversion of forested lands for non-forest uses. Deforestation contributes to increasing carbon dioxide concentrations for two reasons: 1) the burning or decomposition of the wood releases carbon dioxide; and 2) trees that once removed carbon dioxide from the atmosphere in the process of photosynthesis are no longer present.

### Desertification

Land degradation in arid, semi-arid, and dry sub-humid areas resulting from various factors, including climatic variations and human activities. Further, the UNCCD (The United Nations Convention to Combat Desertification) defines land degradation as a reduction or loss, in arid, semi-arid, and dry sub-humid areas, of the biological or economic productivity and complexity of rain-fed cropland, irrigated cropland, or range, pasture, forest, and woodlands resulting from land uses or from a process or combination of processes, including processes arising from human activities and habitation patterns, such as: (i) soil erosion caused by wind and/or water; (ii) deterioration of the physical, chemical and biological or economic properties of soil; and (iii) long-term loss of natural vegetation. Conversion of forest to non-forest.

### Dryland Farming

A technique that uses soil moisture conservation and seed selection to optimize production under dry conditions.

### Earth System

### Eccentricity

The extent to which the Earth's orbit around the Sun departs from a perfect circle.

### Ecosystem

Any natural unit or entity including living and non-living parts that interact to produce a stable system through cyclic exchange of materials.

### El Niño - Southern Oscillation

El Niño, in its original sense, is a warm water current that periodically flows along the coast of Ecuador and Peru, disrupting the local fishery. This oceanic event is associated with a fluctuation of the intertropical surface pressure pattern and circulation in the Indian and Pacific Oceans, called the Southern Oscillation. This coupled atmosphere-ocean phenomenon is collectively known as El Niño-Southern Oscillation. During an El Niño event, the prevailing trade winds weaken and the equatorial countercurrent strengthens, causing warm surface waters in the Indonesian area to flow eastward to overlie the cold waters of the Peru current. This event has great impact on the wind, sea surface temperature, and precipitation patterns in the tropical Pacific. It has climatic effects throughout the Pacific region and in many other parts of the world. The opposite of an El Niño event is called La Niña.

ENSO

### Emissions

The release of a substance (usually a gas when referring to the subject of climate change) into the atmosphere.

### Emissions Factor

A unique value for scaling emissions to activity data in terms of a standard rate of emissions per unit of activity (e.g., grams of carbon dioxide emitted per barrel of fossil fuel consumed, or per pound of product produced).

### Energy Efficiency

Using less energy to provide the same service.

### Energy Star

A U.S. Environmental Protection Agency voluntary program that helps businesses and individuals save money and protect our climate through superior energy efficiency. Learn more about ENERGY STAR (http://www.energystar.gov/index.cfm?c=about.ab\_index).

### Enhanced Greenhouse Effect

The concept that the natural greenhouse effect has been enhanced by increased atmospheric concentrations of greenhouse gases (such as CO₂ and methane) emitted as a result of human activities. These added greenhouse gases cause the earth to warm. See greenhouse effect.

### Enteric Fermentation

Livestock, especially cattle, produce methane as part of their digestion. This process is called enteric fermentation, and it represents one third of the emissions from the agriculture sector.

### Evaporation

The process by which water changes from a liquid to a gas or vapor.

### Evapotranspiration

The combined process of evaporation from the Earth's surface and transpiration from vegetation.

### Feedback Mechanisms

Factors which increase or amplify (positive feedback) or decrease (negative feedback) the rate of a process. An example of positive climatic feedback is the ice-albedo feedback. See climate feedback.

### Fluorinated Gases

Powerful synthetic greenhouse gases such as hydrofluorocarbons, perfluorocarbons, and sulfur hexafluoride that are emitted from a variety of industrial processes. Fluorinated gases are sometimes used as substitutes for stratospheric ozone-depleting substances (e.g., chlorofluorocarbons, hydrochlorofluorocarbons, and halons) and are often used in coolants, foaming agents, fire extinguishers, solvents, pesticides, and aerosol propellants. These gases are emitted in small quantities compared to carbon dioxide (CO₂), methane (CH₄), or nitrous oxide (N₂O), but because they are potent greenhouse gases, they are sometimes referred to as High Global Warming Potential gases (High GWP gases).

### Fluorocarbons

Carbon-fluorine compounds that often contain other elements such as hydrogen, chlorine, or bromine. Common fluorocarbons include chlorofluorocarbons (CFCs), hydrochlorofluorocarbons (HCFCs), hydrofluorocarbons (HFCs), and perfluorocarbons (PFCs). See chlorofluorocarbons, hydrochlorofluorocarbons, hydrofluorocarbons, perfluorocarbons, ozone depleting substance.

### Forcing Mechanism

A process that alters the energy balance of the climate system, i.e. changes the relative balance between incoming solar radiation and outgoing infrared radiation from Earth. Such mechanisms include changes in solar irradiance, volcanic eruptions, and enhancement of the natural greenhouse effect by emissions of greenhouse gases. See radiation, infrared radiation, radiative forcing.

### Fossil Fuel

A general term for organic materials formed from decayed plants and animals that have been converted to crude oil, coal, natural gas, or heavy oils by exposure to heat and pressure in the earth's crust over hundreds of millions of years.

### Fuel Switching

In general, this is substituting one type of fuel for another. In the climate-change discussion it is implicit that the substituted fuel produces lower carbon emissions per unit energy produced than the original fuel, e.g., natural gas for coal.

### General Circulation Model

A global, three-dimensional computer model of the climate system which can be used to simulate human-induced climate change. GCMs are highly complex and they represent the effects of such factors as reflective and absorptive properties of atmospheric water vapor, greenhouse gas concentrations, clouds, annual and daily solar heating, ocean temperatures and ice boundaries. The most recent GCMs include global representations of the atmosphere, oceans, and land surface. See climate modeling.

GCM

### Geosphere

The soils, sediments, and rock layers of the Earth's crust, both continental and beneath the ocean floors.

### Glacier

A multi-year surplus accumulation of snowfall in excess of snowmelt on land and resulting in a mass of ice at least 0.1 km2 in area that shows some evidence of movement in response to gravity. A glacier may terminate on land or in water. Glacier ice is the largest reservoir of fresh water on Earth, and second only to the oceans as the largest reservoir of total water. Glaciers are found on every continent except Australia.

### Global Average Temperature

An estimate of Earth's mean surface air temperature averaged over the entire planet.

### Global Warming

The recent and ongoing global average increase in temperature near the Earth's surface.

### Global Warming Potential

A measure of the total energy that a gas absorbs over a particular period of time (usually 100 years), compared to carbon dioxide.

### Greenhouse Effect

Trapping and build-up of heat in the atmosphere (troposphere) near the Earth's surface. Some of the heat flowing back toward space from the Earth's surface is absorbed by water vapor, carbon dioxide, ozone, and several other gases in the atmosphere and then reradiated back toward the Earth's surface. If the atmospheric concentrations of these greenhouse gases rise, the average temperature of the lower atmosphere will gradually increase. See greenhouse gas, anthropogenic, climate, global warming.

### Greenhouse Gas

Any gas that absorbs infrared radiation in the atmosphere. Greenhouse gases include, carbon dioxide, methane, nitrous oxide, ozone, chlorofluorocarbons, hydrochlorofluorocarbons, hydrofluorocarbons, perfluorocarbons, sulfur hexafluoride.

GHG

### Habitat Fragmentation

A process during which larger areas of habitat are broken into a number of smaller patches of smaller total area, isolated from each other by a matrix of habitats unlike the original habitat. (Fahrig 2003 \[http://www.fs.usda.gov/r1\])

### Halocarbons

Compounds containing either chlorine, bromine or fluorine and carbon. Such compounds can act as powerful greenhouse gases in the atmosphere. The chlorine and bromine containing halocarbons are also involved in the depletion of the ozone layer.

### Heat Island

An urban area characterized by temperatures higher than those of the surrounding non-urban area. As urban areas develop, buildings, roads, and other infrastructure replace open land and vegetation. These surfaces absorb more solar energy, which can create higher temperatures in urban areas.

### Heat Waves

A prolonged period of excessive heat, often combined with excessive humidity.

### Hydrocarbons

Substances containing only hydrogen and carbon. Fossil fuels are made up of hydrocarbons.

### Hydrochlorofluorocarbons

Compounds containing hydrogen, fluorine, chlorine, and carbon atoms. Although ozone depleting substances, they are less potent at destroying stratospheric ozone than chlorofluorocarbons (CFCs). They have been introduced as temporary replacements for CFCs and are also greenhouse gases. See ozone depleting substance.

HCFCs

### Hydrofluorocarbons

Compounds containing only hydrogen, fluorine, and carbon atoms. They were introduced as alternatives to ozone depleting substances in serving many industrial, commercial, and personal needs. HFCs are emitted as by-products of industrial processes and are also used in manufacturing. They do not significantly deplete the stratospheric ozone layer, but they are powerful greenhouse gases with global warming potentials ranging from 140 (HFC-152a) to 11,700 (HFC-23).

HFCs

### Hydrologic Cycle

The process of evaporation, vertical and horizontal transport of vapor, condensation, precipitation, and the flow of water from continents to oceans. It is a major factor in determining climate through its influence on surface vegetation, the clouds, snow and ice, and soil moisture. The hydrologic cycle is responsible for 25 to 30 percent of the mid-latitudes' heat transport from the equatorial to polar regions.

### Hydrosphere

The component of the climate system comprising liquid surface and subterranean water, such as: oceans, seas, rivers, fresh water lakes, underground water etc.

### Ice Core

A cylindrical section of ice removed from a glacier or an ice sheet in order to study climate patterns of the past. By performing chemical analyses on the air trapped in the ice, scientists can estimate the percentage of carbon dioxide and other trace gases in the atmosphere at a given time. Analysis of the ice itself can give some indication of historic temperatures.

### Indirect Emissions

Indirect emissions from a building, home or business are those emissions of greenhouse gases that occur as a result of the generation of electricity used in that building. These emissions are called "indirect" because the actual emissions occur at the power plant which generates the electricity, not at the building using the electricity.

### Industrial Revolution

A period of rapid industrial growth with far-reaching social and economic consequences, beginning in England during the second half of the 18th century and spreading to Europe and later to other countries including the United States. The industrial revolution marks the beginning of a strong increase in combustion of fossil fuels and related emissions of carbon dioxide.

### Infrared Radiation

Infrared radiation consists of light whose wavelength is longer than the red color in the visible part of the spectrum, but shorter than microwave radiation. Infrared radiation can be perceived as heat. The Earth's surface, the atmosphere, and clouds all emit infrared radiation, which is also known as terrestrial or long-wave radiation. In contrast, solar radiation is mainly short-wave radiation because of the temperature of the Sun. See radiation, greenhouse effect, enhanced greenhouse effect, global warming.

### Intergovernmental Panel on Climate Change

The IPCC was established jointly by the United Nations Environment Programme and the World Meteorological Organization in 1988. The purpose of the IPCC is to assess information in the scientific and technical literature related to all significant components of the issue of climate change. The IPCC draws upon hundreds of the world's expert scientists as authors and thousands as expert reviewers. Leading experts on climate change and environmental, social, and economic sciences from some 60 nations have helped the IPCC to prepare periodic assessments of the scientific underpinnings for understanding global climate change and its consequences. With its capacity for reporting on climate change, its consequences, and the viability of adaptation and mitigation measures, the IPCC is also looked to as the official advisory body to the world's governments on the state of the science of the climate change issue. For example, the IPCC organized the development of internationally accepted methods for conducting national greenhouse gas emission inventories.

IPCC

### Inundation

The submergence of land by water, particularly in a coastal setting.

### Landfill

Land waste disposal site in which waste is generally spread in thin layers, compacted, and covered with a fresh layer of soil each day.

### Latitude

The location north or south in reference to the equator, which is designated at zero (0) degrees. Lines of latitude are parallel to the equator and circle the globe. The North and South poles are at 90 degrees North and South latitude.

### Least Developed Country

A country with low indicators of socioeconomic development and human resources, as well as economic vulnerability, as determined by the United Nations.

### Longwave Radiation

Radiation emitted in the spectral wavelength greater than about 4 micrometers, corresponding to the radiation emitted from the Earth and atmosphere. It is sometimes referred to as 'terrestrial radiation' or 'infrared radiation,' although somewhat imprecisely. See infrared radiation.

### Megacities

Cities with populations over 10 million.

### Methane

A hydrocarbon that is a greenhouse gas with a global warming potential most recently estimated at 25 times that of carbon dioxide (CO₂). Methane is produced through anaerobic (without oxygen) decomposition of waste in landfills, animal digestion, decomposition of animal wastes, production and distribution of natural gas and petroleum, coal production, and incomplete fossil fuel combustion. The GWP is from the IPCC's Fourth Assessment Report (AR4). For more information visit EPA's Methane site \[https://www3.epa.gov/climatechange/ghgemissions/gases/ch4.html\].

CH₄

### Metric Ton

Common international measurement for the quantity of greenhouse gas emissions. A metric ton is equal to 2205 lbs or 1.1 short tons. See short ton.

### Mitigation

A human intervention to reduce the human impact on the climate system; it includes strategies to reduce greenhouse gas sources and emissions and enhancing greenhouse gas sinks.

### Mount Pinatubo

A volcano in the Philippine Islands that erupted in 1991. The eruption of Mount Pinatubo ejected enough particulate and sulfate aerosol matter into the atmosphere to block some of the incoming solar radiation from reaching Earth's atmosphere. This effectively cooled the planet from 1992 to 1994, masking the warming that had been occurring for most of the 1980s and 1990s.

### Municipal Solid Waste

Residential solid waste and some non-hazardous commercial, institutional, and industrial wastes. This material is generally sent to municipal landfills for disposal. See landfill.

MSW

### Natural Gas

Underground deposits of gases consisting of 50 to 90 percent methane (CH₄) and small amounts of heavier gaseous hydrocarbon compounds such as propane (C3H8) and butane (C4H10).

### Natural Variability

Variations in the mean state and other statistics (such as standard deviations or statistics of extremes) of the climate on all time and space scales beyond that of individual weather events. Natural variations in climate over time are caused by internal processes of the climate system, such as El Niño, as well as changes in external influences, such as volcanic activity and variations in the output of the sun.

### Nitrogen Cycle

The natural circulation of nitrogen among the atmosphere, plants, animals, and microorganisms that live in soil and water. Nitrogen takes on a variety of chemical forms throughout the nitrogen cycle, including nitrous oxide (N2O) and nitrogen oxides (NOx).

### Nitrogen Oxides

Gases consisting of one molecule of nitrogen and varying numbers of oxygen molecules. Nitrogen oxides are produced in the emissions of vehicle exhausts and from power stations. In the atmosphere, nitrogen oxides can contribute to formation of photochemical ozone (smog), can impair visibility, and have health consequences; they are thus considered pollutants.

NOx

### Nitrous Oxide

A powerful greenhouse gas with a global warming potential of 298 times that of carbon dioxide (CO₂). Major sources of nitrous oxide include soil cultivation practices, especially the use of commercial and organic fertilizers, fossil fuel combustion, nitric acid production, and biomass burning. The GWP is from the IPCC's Fourth Assessment Report (AR4). Natural emissions of N₂O are mainly from bacteria breaking down nitrogen in soils and the oceans. Nitrous oxide is mainly removed from the atmosphere through destruction in the stratosphere by ultraviolet radiation and associated chemical reactions, but it can also be consumed by certain types of bacteria in soils.

N₂O

### Non-Methane Volatile Organic Compounds

Organic compounds, other than methane, that participate in atmospheric photochemical reactions.

NMVOCs

### Ocean Acidification

Increased concentrations of carbon dioxide in sea water causing a measurable increase in acidity (i.e., a reduction in ocean pH). This may lead to reduced calcification rates of calcifying organisms such as corals, mollusks, algae and crustaceans.

### Oxidize

To chemically transform a substance by combining it with oxygen.

### Ozone

Ozone, the triatomic form of oxygen (O₃), is a gaseous atmospheric constituent. In the troposphere, it is created by photochemical reactions involving gases resulting both from natural sources and from human activities (photochemical smog). In high concentrations, tropospheric ozone can be harmful to a wide range of living organisms. Tropospheric ozone acts as a greenhouse gas. In the stratosphere, ozone is created by the interaction between solar ultraviolet radiation and molecular oxygen (O2). Stratospheric ozone plays a decisive role in the stratospheric radiative balance. Depletion of stratospheric ozone, due to chemical reactions that may be enhanced by climate change, results in an increased ground-level flux of ultraviolet (UV-) B radiation. See atmosphere, ultraviolet radiation.

O₃

### Ozone Depleting Substance

A family of man-made compounds that includes, but are not limited to, chlorofluorocarbons (CFCs), bromofluorocarbons (halons), methyl chloroform, carbon tetrachloride, methyl bromide, and hydrochlorofluorocarbons (HCFCs). These compounds have been shown to deplete stratospheric ozone, and therefore are typically referred to as ODSs. See ozone.

ODS

### Ozone Layer

The layer of ozone that begins approximately 15 km above Earth and thins to an almost negligible amount at about 50 km, shields the Earth from harmful ultraviolet radiation from the sun. The highest natural concentration of ozone (approximately 10 parts per million by volume) occurs in the stratosphere at approximately 25 km above Earth. The stratospheric ozone concentration changes throughout the year as stratospheric circulation changes with the seasons. Natural events such as volcanoes and solar flares can produce changes in ozone concentration, but man-made changes are of the greatest concern. See stratosphere, ultraviolet radiation.

### Ozone Precursors

Chemical compounds, such as carbon monoxide, methane, non-methane hydrocarbons, and nitrogen oxides, which in the presence of solar radiation react with other chemical compounds to form ozone, mainly in the troposphere. See troposphere.

### Particulate matter

Very small pieces of solid or liquid matter such as particles of soot, dust, fumes, mists or aerosols. The physical characteristics of particles, and how they combine with other particles, are part of the feedback mechanisms of the atmosphere. See aerosol, sulfate aerosols.

PM

### Parts Per Billion

Number of parts of a chemical found in one billion parts of a particular gas, liquid, or solid mixture. See concentration.

ppb

### Parts Per Million by Volume

Number of parts of a chemical found in one million parts of a particular gas, liquid, or solid. See concentration.

ppmv

### Parts Per Trillion

Number of parts of a chemical found in one trillion parts of a particular gas, liquid or solid. See concentration.

ppt

### Perfluorocarbons

A group of chemicals composed of carbon and fluorine only. These chemicals (predominantly CF4 and C2F6) were introduced as alternatives, along with hydrofluorocarbons, to the ozone depleting substances. In addition, PFCs are emitted as by-products of industrial processes and are also used in manufacturing. PFCs do not harm the stratospheric ozone layer, but they are powerful greenhouse gases: CF4 has a global warming potential (GWP) of 7,390 and C2F6 has a GWP of 12,200. The GWP is from the IPCC's Fourth Assessment Report (AR4). These chemicals are predominantly human-made, though there is a small natural source of CF4. See ozone depleting substance.

### Permafrost

Perennially (continually) frozen ground that occurs where the temperature remains below 0°C for several years.

### PFCs

### Phenology

The timing of natural events, such as flower blooms and animal migration, which is influenced by changes in climate. Phenology is the study of such important seasonal events. Phenological events are influenced by a combination of climate factors, including light, temperature, rainfall, and humidity.

### Photosynthesis

The process by which plants take CO₂ from the air (or bicarbonate in water) to build carbohydrates, releasing O2 in the process. There are several pathways of photosynthesis with different responses to atmospheric CO₂ concentrations. See carbon sequestration, carbon dioxide fertilization.

### Precession

The wobble over thousands of years of the tilt of the Earth's axis with respect to the plane of the solar system.

### Radiation

Energy transfer in the form of electromagnetic waves or particles that release energy when absorbed by an object. See ultraviolet radiation, infrared radiation, solar radiation, longwave radiation.

### Radiative Forcing

A measure of the influence of a particular factor (e.g. greenhouse gas (GHG), aerosol, or land use change) on the net change in the Earth's energy balance.

### Recycling

Collecting and reprocessing a resource so it can be used again. An example is collecting aluminum cans, melting them down, and using the aluminum to make new cans or other aluminum products.

### Reflectivity

The ability of a surface material to reflect sunlight including the visible, infrared, and ultraviolet wavelengths.

### Reforestation

Planting of forests on lands that have previously contained forests but that have been converted to some other use.

### Relative Sea Level Rise

The increase in ocean water levels at a specific location, taking into account both global sea level rise and local factors, such as local subsidence and uplift. Relative sea level rise is measured with respect to a specified vertical datum relative to the land, which may also be changing elevation over time.

### Renewable Energy

Energy resources that are naturally replenishing such as biomass, hydro, geothermal, solar, wind, ocean thermal, wave action, and tidal action.

### Residence Time

The average time spent in a reservoir by an individual atom or molecule. With respect to greenhouse gases, residence time refers to how long on average a particular molecule remains in the atmosphere. For most gases other than methane and carbon dioxide, the residence time is approximately equal to the atmospheric lifetime.

### Resilience

A capability to anticipate, prepare for, respond to, and recover from significant multi-hazard threats with minimum damage to social well-being, the economy, and the environment.

### Respiration

The process whereby living organisms convert organic matter to CO2, releasing energy and consuming O2.

### Salt Water Intrusion

Displacement of fresh or ground water by the advance of salt water due to its greater density, usually in coastal and estuarine areas.

### Scenarios

A plausible and often simplified description of how the future may develop based on a coherent and internally consistent set of assumptions about driving forces and key relationships.

### Sea Surface Temperature

The temperature in the top several feet of the ocean, measured by ships, buoys and drifters.

### Sensitivity

The degree to which a system is affected, either adversely or beneficially, by climate variability or change. The effect may be direct (e.g., a change in crop yield in response to a change in the mean, range or variability of temperature) or indirect (e.g., damages caused by an increase in the frequency of coastal flooding due to sea level rise).

### Short Ton

Common measurement for a ton in the United States. A short ton is equal to 2,000 lbs or 0.907 metric tons. See metric ton.

### Sink

Any process, activity or mechanism which removes a greenhouse gas, an aerosol or a precursor of a greenhouse gas or aerosol from the atmosphere.

### Snowpack

A seasonal accumulation of slow-melting snow.

### Soil Carbon

A major component of the terrestrial biosphere pool in the carbon cycle. The amount of carbon in the soil is a function of the historical vegetative cover and productivity, which in turn is dependent in part upon climatic variables.

### Solar Radiation

Radiation emitted by the Sun. It is also referred to as short-wave radiation. Solar radiation has a distinctive range of wavelengths (spectrum) determined by the temperature of the Sun. See ultraviolet radiation, infrared radiation, radiation.

### Storm Surge

An abnormal rise in sea level accompanying a hurricane or other intense storm, whose height is the difference between the observed level of the sea surface and the level that would have occurred in the absence of the cyclone.

### Stratosphere

Region of the atmosphere between the troposphere and mesosphere, having a lower boundary of approximately 8 km at the poles to 15 km at the equator and an upper boundary of approximately 50 km. Depending upon latitude and season, the temperature in the lower stratosphere can increase, be isothermal, or even decrease with altitude, but the temperature in the upper stratosphere generally increases with height due to absorption of solar radiation by ozone.

### Stratospheric Ozone

See ozone layer.

### Streamflow

The volume of water that moves over a designated point over a fixed period of time. It is often expressed as cubic feet per second (ft3/sec).

### Subsiding/Subsidence

The downward settling of the Earth's crust relative to its surroundings.

### Sulfate Aerosols

Particulate matter that consists of compounds of sulfur formed by the interaction of sulfur dioxide and sulfur trioxide with other compounds in the atmosphere. Sulfate aerosols are injected into the atmosphere from the combustion of fossil fuels and the eruption of volcanoes like Mt. Pinatubo. Sulfate aerosols can lower the Earth's temperature by reflecting away solar radiation (negative radiative forcing). General Circulation Models which incorporate the effects of sulfate aerosols more accurately predict global temperature variations. See particulate matter, aerosol, General Circulation Models.

### Sulfur Hexafluoride

A colorless gas soluble in alcohol and ether, slightly soluble in water. A very powerful greenhouse gas used primarily in electrical transmission and distribution systems and as a dielectric in electronics. The global warming potential of SF6 is 22,800. This GWP is from the IPCC's Fourth Assessment Report (AR4). See Global Warming Potential.

SF6

### Teragram

1 trillion (1012) grams = 1 million (106) metric tons.

### Thermal Expansion

The increase in volume (and decrease in density) that results from warming water. A warming of the ocean leads to an expansion of the ocean volume, which leads to an increase in sea level.

### Thermohaline Circulation

Large-scale density-driven circulation in the ocean, caused by differences in temperature and salinity. In the North Atlantic the thermohaline circulation consists of warm surface water flowing northward and cold deep water flowing southward, resulting in a net poleward transport of heat. The surface water sinks in highly restricted sinking regions located in high latitudes.

### Trace Gas

Any one of the less common gases found in the Earth's atmosphere. Nitrogen, oxygen, and argon make up more than 99 percent of the Earth's atmosphere. Other gases, such as carbon dioxide, water vapor, methane, oxides of nitrogen, ozone, and ammonia, are considered trace gases. Although relatively unimportant in terms of their absolute volume, they have significant effects on the Earth's weather and climate.

### Troposphere

The lowest part of the atmosphere from the surface to about 10 km in altitude in mid-latitudes (ranging from 9 km in high latitudes to 16 km in the tropics on average) where clouds and "weather" phenomena occur. In the troposphere temperatures generally decrease with height. See ozone precursors, stratosphere, atmosphere.

### Tropospheric Ozone

See ozone.

O₃

### Tropospheric Ozone Precursors

See ozone precursors.

### Tundra

A treeless, level, or gently undulating plain characteristic of the Arctic and sub-Arctic regions characterized by low temperatures and short growing seasons.

### Ultraviolet Radiation

The energy range just beyond the violet end of the visible spectrum. Although ultraviolet radiation constitutes only about 5 percent of the total energy emitted from the sun, it is the major energy source for the stratosphere and mesosphere, playing a dominant role in both energy balance and chemical composition. Most ultraviolet radiation is blocked by Earth's atmosphere, but some solar ultraviolet penetrates and aids in plant photosynthesis and helps produce vitamin D in humans. Too much ultraviolet radiation can burn the skin, cause skin cancer and cataracts, and damage vegetation.

UV

### United Nations Framework Convention on Climate Change

The Convention on Climate Change sets an overall framework for intergovernmental efforts to tackle the challenge posed by climate change. It recognizes that the climate system is a shared resource whose stability can be affected by industrial and other emissions of carbon dioxide and other greenhouse gases. The Convention enjoys near universal membership, with 189 countries having ratified. Under the Convention, governments: (1) gather and share information on greenhouse gas emissions, national policies and best practices. (2) launch national strategies for addressing greenhouse gas emissions and adapting to expected impacts, including the provision of financial and technological support to developing countries. (3) cooperate in preparing for adaptation to the impacts of climate change. The Convention entered into force on 21 March 1994.

UNFCCC

### Vulnerability

The degree to which a system is susceptible to, or unable to cope with, adverse effects of climate change, including climate variability and extremes. Vulnerability is a function of the character, magnitude, and rate of climate variation to which a system is exposed; its sensitivity; and its adaptive capacity.

### Wastewater

Water that has been used and contains dissolved or suspended waste materials.

### Water Vapor

The most abundant greenhouse gas, it is the water present in the atmosphere in gaseous form. Water vapor is an important part of the natural greenhouse effect. While humans are not significantly increasing its concentration through direct emissions, it contributes to the enhanced greenhouse effect because the warming influence of greenhouse gases leads to a positive water vapor feedback. In addition to its role as a natural greenhouse gas, water vapor also affects the temperature of the planet because clouds form when excess water vapor in the atmosphere condenses to form ice and water droplets and precipitation. See greenhouse gas.

### Weather

Atmospheric condition at any given time or place. It is measured in terms of such things as wind, temperature, humidity, atmospheric pressure, cloudiness, and precipitation. In most places, weather can change from hour-to-hour, day-to-day, and season-to-season. Climate in a narrow sense is usually defined as the "average weather", or more rigorously, as the statistical description in terms of the mean and variability of relevant quantities over a period of time ranging from months to thousands or millions of years. The classical period is 30 years, as defined by the World Meteorological Organization (WMO). These quantities are most often surface variables such as temperature, precipitation, and wind. Climate in a wider sense is the state, including a statistical description, of the climate system. A simple way of remembering the difference is that climate is what you expect (e.g. cold winters) and 'weather' is what you get (e.g. a blizzard). See climate.